---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# BCRPR

<!-- badges: start -->
<!-- badges: end -->

El objetivo del paquete es Importar datos del BCRP

## Instalaci칩n

Tu puedes instlar esta versi칩n de BCRPR en [CRAN](https://CRAN.R-project.org) con:

``` r
install.packages("BCRPR")
```

Version desarrollada [GitHub](https://github.com/) con:

``` r
# install.packages("devtools")
devtools::install_github("manosaladata/BCRPR")
```
## Ejemplo

Un ejemplo b치sico:

```{r, include = FALSE}
## basic example code
require(jsonlite)
require(ggplot2)
require(lubridate)
require(stringr)
library(foreign)
library(readxl)
library(tidyverse)
require(tidyr)
library(dplyr)
require(plyr)
library(BCRPR)
```

```{r, message = FALSE}
inflacion<-importbcrp('PM05217PA','2010','2020')
plot(inflacion,type = "o",main = "Inflaci칩n Anual 2010-2020")
```
